---
title: "Project-Admission Timestamp--returning deferral"
author: "Wanqi Geng"
date: "25 May 2020 "
output: html_document
---
```{r, include=FALSE}
# General set-up for the report:
# Don't print out code
# Save results so that code blocks aren't re-run unless code
# changes (cache), _or_ a relevant earlier code block changed (autodep),
# don't clutter R output with messages or warnings (message, warning)
library(MASS)  
library(knitr)
library(mapproj)
library(np)
library(ggplot2)
library(gridExtra)
library(broom)
library(dplyr)
opts_chunk$set(echo=FALSE,
               cache=TRUE, autodep=TRUE,
               message=FALSE, warning=FALSE)
# Turn off meaningless clutter in summary() output
options(show.signif.stars=FALSE)
```

```{r, csv-read, include=FALSE}
admission_workflow_data=read.csv("C:/Users/cyh_c/Desktop/gwq/PG_Apps_Workflow_v17.csv",na.strings = c(""))
```

```{r subset3 of dataset, include=FALSE}
subset3_data = subset(admission_workflow_data,select=c(CASE_ID,STU_CITIZEN_NM,STU_ABOR_TSI_NM,SUBMISSION_METHOD,ENTRY_TYPE,LAST_COUNTRY_EDUCATION,PREFERENCE_NO,AVAIL_ORG_UNIT_NM,STUDY_MODE_CD,RETURNING_DEFERRAL,CURR_AVAIL_YR,CURR_STUDY_PERIOD,ORIG_AVAIL_YR,ORIG_STUDY_PERIOD,SPK_CAT_TYPE_CD,OFFER_RELEASED_FG,OFFER_OUTCOME_CD))
```

```{r fix wrong values, include = FALSE}
##change the "Veterinary & Agricultural Sciences" to "Veterinary and Agricultural Sciences"
subset3_data$AVAIL_ORG_UNIT_NM=as.character(subset3_data$AVAIL_ORG_UNIT_NM)
subset3_data$AVAIL_ORG_UNIT_NM[subset3_data$AVAIL_ORG_UNIT_NM == "Veterinary & Agricultural Sciences"]<- "Veterinary and Agricultural Sciences"
subset3_data$AVAIL_ORG_UNIT_NM=as.factor(subset3_data$AVAIL_ORG_UNIT_NM)
```

```{r drop duplicate, include=FALSE}
##81265
subset3_unique_data=subset3_data[!duplicated(subset3_data),]
```

```{r replace na with Not entered,include=FALSE}
subset3_unique_data[1:17]<-lapply(subset3_unique_data[1:17],as.character)
subset3_unique_data[is.na(subset3_unique_data)] <-"Not entered"
subset3_unique_data[1:17]<-lapply(subset3_unique_data[1:17],as.factor)
```

### Response variables:RETURNING_DEFERRAL

```{r predict and fill missing valuesR1,include=FALSE}
subset3_unique_data$OFFER_RELEASED_FG=as.character(subset3_unique_data$OFFER_RELEASED_FG)
##treat "Not entered"" as "N"
subset3_unique_data$OFFER_RELEASED_FG <- ifelse(subset3_unique_data$OFFER_RELEASED_FG=="Not entered","N",subset3_unique_data$OFFER_RELEASED_FG)
subset3_unique_data$OFFER_RELEASED_FG=as.factor(subset3_unique_data$OFFER_RELEASED_FG)
```

```{r drop OFFER_RELEASED_FG == "N", include = FALSE}
subset3_unique_data <- subset3_unique_data[!(subset3_unique_data$OFFER_RELEASED_FG == "N"),]
```

```{r values-R2, include=FALSE}
#39002
##Pre-request OFFER_RELEASED_FG == "Y"
##NA exsits 13826 not answer? maybe we can combine it with lapse109??
count(subset3_unique_data,OFFER_OUTCOME_CD)
```

```{r predict and fill missing valuesR2,include=FALSE}
subset3_unique_data$OFFER_OUTCOME_CD=as.character(subset3_unique_data$OFFER_OUTCOME_CD)
##treat "NA"as "$LAP" 
subset3_unique_data$OFFER_OUTCOME_CD <- ifelse(subset3_unique_data$OFFER_OUTCOME_CD=="NA","$LAP",subset3_unique_data$OFFER_OUTCOME_CD)
subset3_unique_data$OFFER_OUTCOME_CD=as.factor(subset3_unique_data$OFFER_OUTCOME_CD)
```

```{r select OFFER_OUTCOME_CD == "$DEF"}
subset3_unique_data <- subset3_unique_data[(subset3_unique_data$OFFER_OUTCOME_CD == "$DEF"),]
```

```{r values-R3, include=FALSE}
count(subset3_unique_data,RETURNING_DEFERRAL)
```

###Initial Summary Observations

```{r PROP TABLE 1, echo = FALSE}
##proportion 
prop.table(table(subset3_unique_data$STU_CITIZEN_NM))
prop.table(table(subset3_unique_data$STU_CITIZEN_NM,subset3_unique_data$RETURNING_DEFERRAL),1)
```

```{r PROP TABLE 2, echo = FALSE}
prop.table(table(subset3_unique_data$STU_ABOR_TSI_NM))
prop.table(table(subset3_unique_data$STU_ABOR_TSI_NM,subset3_unique_data$RETURNING_DEFERRAL),1)
```

```{r PROP TABLE 3, echo = FALSE}
prop.table(table(subset3_unique_data$SUBMISSION_METHOD))
prop.table(table(subset3_unique_data$SUBMISSION_METHOD,subset3_unique_data$RETURNING_DEFERRAL),1)
```

```{r PROP TABLE 4, echo = FALSE}
prop.table(table(subset3_unique_data$ENTRY_TYPE))
prop.table(table(subset3_unique_data$ENTRY_TYPE,subset3_unique_data$RETURNING_DEFERRAL),1)
```


```{r PROP TABLE 5, echo = FALSE}
prop.table(table(subset3_unique_data$LAST_COUNTRY_EDUCATION))
prop.table(table(subset3_unique_data$LAST_COUNTRY_EDUCATION,subset3_unique_data$RETURNING_DEFERRAL),1)
```

```{r PROP TABLE 6, echo = FALSE}
prop.table(table(subset3_unique_data$PREFERENCE_NO))
prop.table(table(subset3_unique_data$PREFERENCE_NO,subset3_unique_data$RETURNING_DEFERRAL),1)
```

```{r PROP TABLE 7, echo = FALSE}
prop.table(table(subset3_unique_data$STUDY_MODE_CD))
prop.table(table(subset3_unique_data$AVAIL_ORG_UNIT_NM,subset3_unique_data$RETURNING_DEFERRAL),1)
```

```{r PROP TABLE 8, echo = FALSE}
prop.table(table(subset3_unique_data$CURR_AVAIL_YR))
prop.table(table(subset3_unique_data$CURR_AVAIL_YR,subset3_unique_data$RETURNING_DEFERRAL),1)
```

```{r PROP TABLE 9, echo = FALSE}
prop.table(table(subset3_unique_data$CURR_STUDY_PERIOD))
prop.table(table(subset3_unique_data$CURR_STUDY_PERIOD,subset3_unique_data$RETURNING_DEFERRAL),1)
```

```{r PROP TABLE 10, echo = FALSE}
prop.table(table(subset3_unique_data$ORIG_AVAIL_YR))
prop.table(table(subset3_unique_data$ORIG_AVAIL_YR,subset3_unique_data$RETURNING_DEFERRAL),1)
```

```{r PROP TABLE 11, echo = FALSE}
prop.table(table(subset3_unique_data$ORIG_STUDY_PERIOD))
prop.table(table(subset3_unique_data$ORIG_STUDY_PERIOD,subset3_unique_data$RETURNING_DEFERRAL),1)
```
```{r PROP TABLE 12, echo = FALSE}
prop.table(table(subset3_unique_data$SPK_CAT_TYPE_CD))
prop.table(table(subset3_unique_data$SPK_CAT_TYPE_CD,subset3_unique_data$RETURNING_DEFERRAL),1)
```

```{r plot1,2,3,4,fig.align='center', fig.width= 20, fig.height = 16,echo=FALSE}
p1=ggplot(data=subset3_unique_data, aes(RETURNING_DEFERRAL,..count..))+geom_bar(aes(fill=STU_CITIZEN_NM),position="dodge")+ggtitle("visa status vs. returning deferral")
p2=ggplot(data=subset3_unique_data, aes(RETURNING_DEFERRAL,..count..))+geom_bar(aes(fill=STU_ABOR_TSI_NM),position="dodge")+ggtitle("aboriginal and torres strait islander status vs. returning deferral")
p3=ggplot(data=subset3_unique_data, aes(RETURNING_DEFERRAL,..count..))+geom_bar(aes(fill=SUBMISSION_METHOD),position="dodge")+ggtitle("submission method vs. returning deferral")
p4=ggplot(data=subset3_unique_data, aes(RETURNING_DEFERRAL,..count..))+geom_bar(aes(fill=ENTRY_TYPE),position="dodge")+ggtitle("entry type vs. returning deferral")
grid.arrange(p1,p2,p3,p4,ncol=2)
```


```{r plot5,fig.align='center', fig.width= 24, fig.height = 10,echo=FALSE}
p5=ggplot(data=subset3_unique_data, aes(RETURNING_DEFERRAL,..count..))+geom_bar(aes(fill=LAST_COUNTRY_EDUCATION),position="dodge")+ggtitle("last country of education vs. returning deferral")
p5
```

```{r plot6,7,8,9,10,11,12,fig.align='center', fig.width= 22, fig.height = 20,echo=FALSE}
p6=ggplot(data=subset3_unique_data, aes(RETURNING_DEFERRAL,..count..))+geom_bar(aes(fill=PREFERENCE_NO),position="dodge")+ggtitle("Prefernece number vs. returning deferral")
p7=ggplot(data=subset3_unique_data, aes(RETURNING_DEFERRAL,..count..))+geom_bar(aes(fill=STUDY_MODE_CD),position="dodge")+ggtitle("Study mode vs. returning deferral")
p8=ggplot(data=subset3_unique_data, aes(RETURNING_DEFERRAL,..count..))+geom_bar(aes(fill=CURR_AVAIL_YR),position="dodge")+ggtitle("current available year vs. returning deferral")
p9=ggplot(data=subset3_unique_data, aes(RETURNING_DEFERRAL,..count..))+geom_bar(aes(fill=CURR_STUDY_PERIOD),position="dodge")+ggtitle("current available period vs. returning deferral")
p10=ggplot(data=subset3_unique_data, aes(RETURNING_DEFERRAL,..count..))+geom_bar(aes(fill=ORIG_AVAIL_YR),position="dodge")+ggtitle("Original available year vs. returning deferral")
p11=ggplot(data=subset3_unique_data, aes(RETURNING_DEFERRAL,..count..))+geom_bar(aes(fill=ORIG_STUDY_PERIOD),position="dodge")+ggtitle("Original available period vs. returning deferral")
p12=ggplot(data=subset3_unique_data, aes(RETURNING_DEFERRAL,..count..))+geom_bar(aes(fill=SPK_CAT_TYPE_CD),position="dodge")+ggtitle("level of study vs. returning deferral")
grid.arrange(p6,p7,p8,p9,p10,p11,p12,ncol=2)
```